### ISSUE TITLE
Stream video from a python program and play it in browser?

### ISSUE THREAD

**Issue by yasersakkaf** [anyaudio/anyaudio-server#164]
I have a video in my laptop.
I want to stream it to another machine and play the video in the other machine's browser.
Do you have any idea how I can achieve this?

**Comment by singhpratyush** [comment]
This issue is not related to this repository.

If you are a developer, you can use `flask` to serve the files. You'll need to handle the partial content thing carefully as you won't be able to seek the video without it.

There is this project which I made during my college days which might help you - https://github.com/iiitv/mediavault. It has ZERO documentation so if you need help with something, just open an issue.

Cheers :beer:
